"""remove last seen

Revision ID: 83827dd854df
Revises: c59ded0c6a38
Create Date: 2025-08-26 22:27:50.183208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83827dd854df'
down_revision = 'c59ded0c6a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
